# Generated by Django 2.1.5 on 2019-01-11 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190111_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='reader',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL),
        ),
    ]
