# Generated by Django 2.1.5 on 2019-01-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190111_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='readers',
        ),
        migrations.AddField(
            model_name='read',
            name='posts',
            field=models.ManyToManyField(to='blog.Post'),
        ),
    ]
