# Generated by Django 2.1.5 on 2019-01-12 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='users_like',
        ),
        migrations.AddField(
            model_name='post',
            name='users_readers',
            field=models.ManyToManyField(blank=True, related_name='posts_readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
